/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookstore.jooq.models.tables;


import com.sivalabs.bookstore.jooq.models.Keys;
import com.sivalabs.bookstore.jooq.models.Public;
import com.sivalabs.bookstore.jooq.models.tables.records.OrdersRecord;

import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function15;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row15;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders extends TableImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.orders</code>
     */
    public static final Orders ORDERS = new Orders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrdersRecord> getRecordType() {
        return OrdersRecord.class;
    }

    /**
     * The column <code>public.orders.id</code>.
     */
    public final TableField<OrdersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.orders.order_number</code>.
     */
    public final TableField<OrdersRecord, String> ORDER_NUMBER = createField(DSL.name("order_number"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.customer_name</code>.
     */
    public final TableField<OrdersRecord, String> CUSTOMER_NAME = createField(DSL.name("customer_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.customer_email</code>.
     */
    public final TableField<OrdersRecord, String> CUSTOMER_EMAIL = createField(DSL.name("customer_email"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.customer_phone</code>.
     */
    public final TableField<OrdersRecord, String> CUSTOMER_PHONE = createField(DSL.name("customer_phone"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.delivery_address_line1</code>.
     */
    public final TableField<OrdersRecord, String> DELIVERY_ADDRESS_LINE1 = createField(DSL.name("delivery_address_line1"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.delivery_address_line2</code>.
     */
    public final TableField<OrdersRecord, String> DELIVERY_ADDRESS_LINE2 = createField(DSL.name("delivery_address_line2"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.orders.delivery_address_city</code>.
     */
    public final TableField<OrdersRecord, String> DELIVERY_ADDRESS_CITY = createField(DSL.name("delivery_address_city"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.delivery_address_state</code>.
     */
    public final TableField<OrdersRecord, String> DELIVERY_ADDRESS_STATE = createField(DSL.name("delivery_address_state"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.delivery_address_zip_code</code>.
     */
    public final TableField<OrdersRecord, String> DELIVERY_ADDRESS_ZIP_CODE = createField(DSL.name("delivery_address_zip_code"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.delivery_address_country</code>.
     */
    public final TableField<OrdersRecord, String> DELIVERY_ADDRESS_COUNTRY = createField(DSL.name("delivery_address_country"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.status</code>.
     */
    public final TableField<OrdersRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.orders.comments</code>.
     */
    public final TableField<OrdersRecord, String> COMMENTS = createField(DSL.name("comments"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.orders.created_at</code>.
     */
    public final TableField<OrdersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.orders.updated_at</code>.
     */
    public final TableField<OrdersRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private Orders(Name alias, Table<OrdersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Orders(Name alias, Table<OrdersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.orders</code> table reference
     */
    public Orders(String alias) {
        this(DSL.name(alias), ORDERS);
    }

    /**
     * Create an aliased <code>public.orders</code> table reference
     */
    public Orders(Name alias) {
        this(alias, ORDERS);
    }

    /**
     * Create a <code>public.orders</code> table reference
     */
    public Orders() {
        this(DSL.name("orders"), null);
    }

    public <O extends Record> Orders(Table<O> child, ForeignKey<O, OrdersRecord> key) {
        super(child, key, ORDERS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OrdersRecord, Long> getIdentity() {
        return (Identity<OrdersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrdersRecord> getPrimaryKey() {
        return Keys.ORDERS_PKEY;
    }

    @Override
    public Orders as(String alias) {
        return new Orders(DSL.name(alias), this);
    }

    @Override
    public Orders as(Name alias) {
        return new Orders(alias, this);
    }

    @Override
    public Orders as(Table<?> alias) {
        return new Orders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Orders rename(String name) {
        return new Orders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orders rename(Name name) {
        return new Orders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orders rename(Table<?> name) {
        return new Orders(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function15<? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function15<? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
