/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookstore.jooq.models.tables.records;


import com.sivalabs.bookstore.jooq.models.tables.Products;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> implements Record6<Long, String, String, String, String, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.products.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.products.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.products.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.products.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.products.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.products.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.products.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.products.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.products.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.products.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.products.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.products.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, String, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, String, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Products.PRODUCTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Products.PRODUCTS.CODE;
    }

    @Override
    public Field<String> field3() {
        return Products.PRODUCTS.NAME;
    }

    @Override
    public Field<String> field4() {
        return Products.PRODUCTS.DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return Products.PRODUCTS.IMAGE_URL;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Products.PRODUCTS.PRICE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getImageUrl();
    }

    @Override
    public BigDecimal component6() {
        return getPrice();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public String value5() {
        return getImageUrl();
    }

    @Override
    public BigDecimal value6() {
        return getPrice();
    }

    @Override
    public ProductsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProductsRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public ProductsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProductsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ProductsRecord value5(String value) {
        setImageUrl(value);
        return this;
    }

    @Override
    public ProductsRecord value6(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public ProductsRecord values(Long value1, String value2, String value3, String value4, String value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(Long id, String code, String name, String description, String imageUrl, BigDecimal price) {
        super(Products.PRODUCTS);

        setId(id);
        setCode(code);
        setName(name);
        setDescription(description);
        setImageUrl(imageUrl);
        setPrice(price);
        resetChangedOnNotNull();
    }
}
