/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookstore.jooq.models;


import com.sivalabs.bookstore.jooq.models.tables.OrderItems;
import com.sivalabs.bookstore.jooq.models.tables.Orders;
import com.sivalabs.bookstore.jooq.models.tables.Products;
import com.sivalabs.bookstore.jooq.models.tables.records.OrderItemsRecord;
import com.sivalabs.bookstore.jooq.models.tables.records.OrdersRecord;
import com.sivalabs.bookstore.jooq.models.tables.records.ProductsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OrderItemsRecord> ORDER_ITEMS_PKEY = Internal.createUniqueKey(OrderItems.ORDER_ITEMS, DSL.name("order_items_pkey"), new TableField[] { OrderItems.ORDER_ITEMS.ID }, true);
    public static final UniqueKey<OrdersRecord> ORDERS_PKEY = Internal.createUniqueKey(Orders.ORDERS, DSL.name("orders_pkey"), new TableField[] { Orders.ORDERS.ID }, true);
    public static final UniqueKey<ProductsRecord> PRODUCTS_CODE_KEY = Internal.createUniqueKey(Products.PRODUCTS, DSL.name("products_code_key"), new TableField[] { Products.PRODUCTS.CODE }, true);
    public static final UniqueKey<ProductsRecord> PRODUCTS_PKEY = Internal.createUniqueKey(Products.PRODUCTS, DSL.name("products_pkey"), new TableField[] { Products.PRODUCTS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<OrderItemsRecord, OrdersRecord> ORDER_ITEMS__ORDER_ITEMS_ORDER_ID_FKEY = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("order_items_order_id_fkey"), new TableField[] { OrderItems.ORDER_ITEMS.ORDER_ID }, Keys.ORDERS_PKEY, new TableField[] { Orders.ORDERS.ID }, true);
}
