/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookstore.jooq.models;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.order_id_seq</code>
     */
    public static final Sequence<Long> ORDER_ID_SEQ = Internal.createSequence("order_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100, 50, null, null, false, null);

    /**
     * The sequence <code>public.order_item_id_seq</code>
     */
    public static final Sequence<Long> ORDER_ITEM_ID_SEQ = Internal.createSequence("order_item_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100, 50, null, null, false, null);

    /**
     * The sequence <code>public.product_id_seq</code>
     */
    public static final Sequence<Long> PRODUCT_ID_SEQ = Internal.createSequence("product_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100, 50, null, null, false, null);
}
