/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookstore.jooq.models;


import com.sivalabs.bookstore.jooq.models.tables.OrderItems;
import com.sivalabs.bookstore.jooq.models.tables.Orders;
import com.sivalabs.bookstore.jooq.models.tables.Products;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.order_items</code>.
     */
    public static final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;
}
